language: java
jdk:
  - oraclejdk8
services:
  - postgresql: "9.6"
before_script:
  - psql -c 'create database javaserverdb;' -U postgres
env:
  - JDBC_DATABASE_URL=jdbc:postgresql://localhost:5432/javaserverdb JDBC_DATABASE_USERNAME=postgres JDBC_DATABASE_PASSWORD=
